# Generated by Django 3.0.2 on 2020-01-13 14:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите цвет (Например: Желтый)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Введите краткое описание', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('color', models.ManyToManyField(help_text='Выбери цвета для букета', to='catalog.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите форму (Например: Букет)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KindOfFlower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('sale_time', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('o', 'В наличии'), ('x', 'Нет в наличии')], default='o', help_text='Есть/Нет в наличии', max_length=1)),
                ('flower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Flower')),
            ],
            options={
                'ordering': ['sale_time'],
            },
        ),
        migrations.AddField(
            model_name='flower',
            name='kind_of_flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.KindOfFlower'),
        ),
    ]
