# Generated by Django 3.0.2 on 2020-01-14 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='flowerinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID', primary_key=True, serialize=False),
        ),
    ]
