# Generated by Django 3.0.2 on 2020-01-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200114_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowerinstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='flowerinstance',
            name='sale_time',
        ),
    ]
