# Generated by Django 3.0.2 on 2020-01-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200114_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlowerInstance',
            new_name='ForSale',
        ),
    ]
